fn main() {
    // The Tauri bootstrap is generated by `build:tauri-bootstrap`. Raw
    // `cargo build` is also used by the packaging and local replacement
    // flows, so make the generated frontend an explicit build input rather
    // than silently reusing a binary that embedded an older (or empty)
    // bootstrap directory.
    println!("cargo:rerun-if-changed=../dist-tauri");
    // `cargo check`/`cargo test` validate Tauri resources before the packaging
    // scripts have generated the PyInstaller sidecar. Keep release builds strict
    // while allowing local Rust checks to run in a clean checkout.
    if std::env::var("PROFILE").as_deref() != Ok("release") {
        let _ = std::fs::create_dir_all("binaries/qwenpaw-backend");
    }

    tauri_build::build()
}
